### ISSUE TITLE
The example code does not work under Ubuntu 23.10 with python 3.11.6

### ISSUE THREAD

**Issue by atellyro** [bbc6502/gedcom5#1]
Running your example I get

test-read-gedcom5.py
Traceback (most recent call last):
  File "/dosd/bin/test-read-gedcom5.py", line 19, in <module>
    gedcom.indi[0].name.value == 'Bob /BROWN/'
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'value'

I like your parser, because I can access the parts by name (e.g. .name)

**Comment by atellyro** [comment]
The version is 
Downloading gedcom5-0.1.9-py3-none-any.whl (14 kB)
Installing collected packages: gedcom5
Successfully installed gedcom5-0.1.9

installed with pip3

**Comment by bbc6502** [comment]
Hello,
Thank you for letting me know that the example in the readme was not correct.
I have updated the readme with the corrected example and included the example in the test suite.
The new version is 0.2.0 and is on pypi now.
Thank you
